package com.esgbank.greenbond.monitoring.model.enums;

public enum MetricType {
    // Environmental Metrics
    CARBON_EMISSIONS_REDUCTION,
    RENEWABLE_ENERGY_PRODUCTION,
    ENERGY_CONSUMPTION,
    WATER_SAVINGS,
    WASTE_REDUCTION,
    RECYCLING_RATE,
    AIR_QUALITY_IMPROVEMENT,
    BIODIVERSITY_IMPACT,

    // Social Metrics
    JOBS_CREATED,
    COMMUNITY_ENGAGEMENT,
    HEALTH_IMPROVEMENT,
    EDUCATION_ACCESS,
    AFFORDABLE_HOUSING,

    // Economic Metrics
    LOCAL_ECONOMIC_GROWTH,
    TAX_REVENUE_GENERATED,
    COST_SAVINGS,
    REVENUE_GENERATED,

    // Project Specific
    SOLAR_ENERGY_GENERATED,
    WIND_ENERGY_GENERATED,
    GREEN_BUILDING_CERTIFICATION,
    CLEAN_TRANSPORT_USAGE,
    SUSTAINABLE_WATER_MANAGEMENT
}